spring:
  application:
    name: vocalchat
  datasource:
    url: jdbc:mysql://localhost:3306/vocalchat?useSSL=false&serverTimezone=UTC
    username: Hunger
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mail:
    host: smtp.qq.com
    port: 587
    username: 3287426755@qq.com
    password: vothdaqxyvfhdbeg
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: jwt
  expiration: 86400